sudo:required
services:
        - docker

before_install:
        - docker build - kamathn/react-complex-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true kamathn/react-complex-test npm test

after_success:
        - docker build -t kamathn/multi-complex-client ./client
        - docker build -t kamathn/multi-complex-nginx ./nginx
        - docker build -t kamathn/multi-complex-server./server
        - docker build -t kamathn/multi-complex-worker ./worker
        

